mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.urls import re_path
from stocks import views
# from previews.Stock import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stocks.urls',namespace='stocks')),
    # re_path(r'^$', views.index),
    # re_path(r'^data_entry/$', views.data_entry, name='data_entry'),
    # re_path(r'^add_fund_manger/$', views.add_fund_manger),
    # re_path(r'^add_stock/$', views.add_stock),
    # re_path(r'^check$', views.check_index, name='check'),
    # re_path(r'^trading/$', views.check),
    # re_path(r'^trading_success/$', views.trading),
    # re_path(r'^fund_pool/$', views.Fund_pool_, name='fund_pool'),
    # re_path(r'^account/$', views.Account)
]

stocks/urls.py
from django.urls import path,re_path
from . import views

app_name = 'stocks'

urlpatterns = [
 path('', views.index, name='index'),
 path('buystock/', views.buystock, name='buystock'),
 path('trade/', views.trade, name='trade'),
 path('sellstock/', views.sellstock, name='sellstock'),
 path('stockinhand/', views.stock_inhand, name='stockinhand'),
 # path('detail/(?P<code>)',views.stockdetail,name='stockdetail'),
 re_path(r'^detail/(?P<code>\d{5,6})/$', views.stockdetail, name='stockdetail'),
 path('profit/', views.profit, name='profit'),
 path('total/', views.total, name='total'),
 # path('lowmarketcap/', views.lowmarketcap, name='lowmarketcap'),
 # path('totalbench/', views.totalbench, name='totalbench'),
 # path('cleandata/', views.cleandata, name='cleandata'),
]

templates/base.html
<!Doctype html>
{% load static %}
<html>
<head>
	<meta  content="text/html;  charset=UTF-8" />
	<title>
		{% block title %}
		{% endblock %}
	</title>

	{% block head %}
	{% endblock %}
    <link rel="icon" href="{% static 'images/favicon.ico' %}">

</head>


<body>

<a  href="{% url 'stocks:index' %}" >首页</a>
<a  href="{% url 'stocks:trade' %}" >数据输入</a>
<a  href="{% url 'stocks:stockinhand' %}">持仓</a>
<a  href="{% url 'stocks:profit' %}">亏钱的艺术</a>



<div class="container">
 {% block content %}

 {% endblock %}
 </div>

 {% block javascript %}

 {% endblock %}

 {% block css %}

 {% endblock %}


</body>

</html>

templates/example.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}
Index
{% endblock %}


{% block content %}
    <h1>welcome，it just is a cover </h1>
<!--    {#<a  href="{% url 'stocks:detail/{{ stock.code }}' %}" >持仓</a>#}-->
<!--    <h3>一些小市值的股票,现金{{cash}}可挥霍:今天{{low_market_tip}}</h3>-->
<!--     <h3>看看SVR,还有{{svr_cash}}可挥霍:今天{{low_market_tip}}</h3>-->

<!--    <div class="stocklist" id="lowmarketcap">-->
<!--        {{ table | safe }}-->
<!--    </div>-->
<!--    <br>-->
    <div class="stocklist" id="hotrank">
        <h3>东财热股</h3>
        {{ hot_rank_em_df_html | safe }}
    </div>
    <div class="stocklist" id="hotup">
        <h3>东财飙升</h3>
        {{ hot_up_em_df_html | safe }}
    </div>


<!-- <form name="cleanform"  action="/cleandata/"  method="POST">-->
<!--        {% csrf_token %}-->

<!--    <input style=" "     type="submit" name="clean" value="Clean" />-->
<!-- </form>-->


{% endblock %}

templates/lowmarketcap.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
lowmarketcap
{% endblock %}

{% block head %}
    <style>
     .div-left{float:left}

    </style>
    <script type="text/javascript" src="{% static 'js/echarts.min.js' %}"></script>

{% endblock %}


{% block content %}
<h1>小市值的股票</h1>
<h3>还有现金{{cash}}</h3>
<div>
    {{table|safe}}
</div>
<br>


<div>
    <img src="{{ img }}">
<!--    <img src="my_plot.png" >-->
</div>


<div id="new_container" style="width: 800px;height:400px;"></div>
     <script type="text/javascript">
    var dom = document.getElementById("new_container");
    var myChart = echarts.init(dom);

    var series_data = [];
    var xAxis_data_300 = [];
    var xAxis_data_value = [];

    {% for date in dates %}
        series_data.push("{{ date }}")
    {% endfor %}

    {% for data in benchs %}
        xAxis_data_300.push("{{ data }}")
    {% endfor %}

    {% for data in strategys %}
        xAxis_data_value.push("{{ data }}")
    {% endfor %}


    option = {
    title: {
        text: '小市值__echart'
    },
    tooltip: {},

    legend: {
        data1: ['沪深300'],
        data2: ['小市值'],
    },

    xAxis: {
            data: series_data,
    },

    yAxis: {},

    series: [{
        name: '沪深300',
        type: 'line',
        data: xAxis_data_300,
        smooth: true
    },

    {
        name: '你的资产',
        type: 'line',
        data: xAxis_data_value,
        smooth: true,
        color: 'red',
    },

    ]
    };
    myChart.setOption(option);
    </script>

{% endblock %}

templates/profit.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Profit
{% endblock %}

{% block head %}
<script type="text/javascript" src="{% static 'js/echarts.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/echarts.min.js' %}"></script>
{% endblock %}



{% block content %}

<h1>welcome，it just is an example</h1>
<h3>每天都在亏钱</h3>
<img src="data:image/png;base64,{{ graphic2 }}" alt="Plot">
<h3>和沪深300 比比看</h3>
<img src="data:image/png;base64,{{ graphic1 }}" alt="Plot">

<div id="profit_day" style="width: 800px;height:300px;"></div>
<script type="text/javascript">

<!--    // 基于准备好的dom，初始化echarts实例-->
<!--    var myChart = echarts.init(document.getElementById('profit_day'));-->

<!--    // 指定图表的配置项和数据-->
<!--    var series_data = [];-->
<!--    var xAxis_data = [];-->

<!--    {% for profit in profits %}-->
<!--    series_data.push({{ profit.profit }})-->
<!--    { #注意这里的双引号# }-->
<!--    xAxis_data.push("{{ profit.date}}")-->
<!--    {% endfor %}-->

<!--    var option = {-->
<!--        title: {-->
<!--            text: '亏钱的艺术'-->
<!--        },-->
<!--        tooltip: {},-->
<!--        legend: {-->
<!--            data: ['亏钱']-->
<!--        },-->
<!--        xAxis: {-->
<!--            data: xAxis_data-->
<!--        },-->
<!--        yAxis: {-->
<!--            axisLabel: {-->
<!--                formatter: '{value} 元'-->
<!--            },-->
<!--        },-->
<!--        series: [-->
<!--            {-->
<!--                name: '亏钱',-->
<!--                type: 'bar',-->
<!--                data: series_data-->
<!--            }-->
<!--        ]-->
<!--    };-->
<!--    // 使用刚指定的配置项和数据显示图表。-->
<!--    myChart.setOption(option);-->
<!--</script>-->


<!--<div id="container" style="width: 800px;height:300px;"></div>-->
<!--<script type="text/javascript">-->
<!--                var dom = document.getElementById("container");-->
<!--                var myChart = echarts.init(dom);-->

<!--                var series_data = [];-->
<!--                var xAxis_data_300 = [];-->
<!--                var xAxis_data_total = [];-->

<!--                {% for bench in bench2total %}-->
<!--                series_data.push("{{ bench.date }}")-->
<!--                { #注意这里的双引号# }-->
<!--                xAxis_data_300.push("{{ bench.bench_ratio}}")-->
<!--                xAxis_data_total.push("{{ bench.total_ratio}}")-->
<!--                {% endfor %}-->


<!--                option = {-->
<!--                    title: {-->
<!--                        text: '对比300'-->
<!--                    },-->
<!--                    tooltip: {},-->

<!--                    legend: {-->
<!--                        data1: ['沪深300'],-->
<!--                        data2: ['你的资产'],-->
<!--                    },-->

<!--                    xAxis: {-->
<!--                        data: series_data-->
<!--                    },-->

<!--                    yAxis: {-->
<!--                        axisLabel: {-->
<!--                            formatter: '{value} %'-->
<!--                        },-->

<!--                    },-->

<!--                    series: [{-->
<!--                        name: '沪深300',-->
<!--                        type: 'line',-->
<!--                        //data: [5, 20, 36, 10, 10, 20]-->
<!--                        data: xAxis_data_300,-->
<!--                        smooth: true-->
<!--                    },-->

<!--                    {-->
<!--                        name: '你的资产',-->
<!--                        type: 'line',-->
<!--                        //data: [5, 20, 36, 10, 10, 20]-->
<!--                        data: xAxis_data_total,-->
<!--                        smooth: true,-->
<!--                        color: 'red',-->
<!--                    },-->

<!--                    ]-->
<!--                };-->
<!--                myChart.setOption(option);-->
<!--</script>-->


<!--<div id="svr_curve" style="width: 800px;height:300px;"></div>-->
<!--<script type="text/javascript">-->
<!--                var dom = document.getElementById("svr_curve");-->
<!--                var myChart = echarts.init(dom);-->

<!--                var series_data = [];-->
<!--                var xAxis_data_300 = [];-->
<!--                var xAxis_data_value = [];-->

<!--                {% for bench in bench2svr %}-->
<!--                series_data.push("{{ bench.date }}")-->
<!--                { #注意这里的双引号# }-->
<!--                xAxis_data_300.push("{{ bench.bench_ratio}}")-->
<!--                xAxis_data_value.push("{{ bench.value_ratio}}")-->
<!--                {% endfor %}-->

<!--                option = {-->
<!--                    title: {-->
<!--                        text: 'svr__echart'-->
<!--                    },-->
<!--                    tooltip: {},-->

<!--                    legend: {-->
<!--                        data1: ['沪深300'],-->
<!--                        data2: ['svr'],-->
<!--                    },-->

<!--                    xAxis: {-->
<!--                        data: series_data,-->
<!--                    },-->

<!--                    yAxis: {-->
<!--                        axisLabel: {-->
<!--                            formatter: '{value} %'-->
<!--                        },-->

<!--                    },-->

<!--                    series: [{-->
<!--                        name: '沪深300',-->
<!--                        type: 'line',-->
<!--                        data: xAxis_data_300,-->
<!--                        smooth: true-->
<!--                    },-->

<!--                    {-->
<!--                        name: 'svr',-->
<!--                        type: 'line',-->
<!--                        data: xAxis_data_value,-->
<!--                        smooth: true,-->
<!--                        color: 'red',-->
<!--                    },-->

<!--                    ]-->
<!--                };-->
<!--                myChart.setOption(option);-->
<!--</script>-->



{% endblock %}

templates/stockdetail.html
{% extends 'base.html' %}

{% block title %}
Detail
{% endblock %}

{% block head %}
    <style>
     .div-left{float:left}

    </style>
{% endblock %}


{% block content %}
<h1>welcome，it just is an example</h1>
<table>
    <tr>
        <td>代码</td>
        <td>{{ stock.code }}</td>
    </tr>
    <tr>
        <td>名称</td>
       <td>{{ stock.name }}</td>
    </tr>
    <tr>
        <td>最新价格</td>
       <td>{{ stock.close }}</td>
    </tr>
    <tr>
        <td>持有</td>
       <td>{{ stock.quantityinhand }}</td>
    </tr>
    <tr>
        <td>市值</td>
        <td>{{ stock.value }}</td>
    </tr>
    <tr>
        <td>收益</td>
        <td>{{ stock.profit }}</td>
    </tr>
    <tr>
		  <td> 估值</td>
		  <td>{{ stock.estimation }}</td>
 </tr>
</table>
<p>
交易记录
</p>
    <div class='table_record' style="text-align: center;">
<table border="1">
      <tr>
		  <th>时间</th>
		  <th>股票代码</th>
		  <th>股票名称</th>
		  <th>操作</th>
		  <th>数量</th>
		  <th>价格</th>
		  <th>金额</th>
	  </tr>
	{% for item in records %}
      <tr>
		  <td>{{ item.date }}</td>
		  <td> {{ item.stock.code }} </td>
		   <td><a  href="{% url 'stocks:stockdetail' item.stock.code %}" > {{ item.stock.name }} </a></td>
		  <td>{{ item.mark }}</td>
		  <td>{{ item.quantity }}</td>
		  <td>{{ item.price }}</td>
		  <td>{{ item.amount }}</td>
	  </tr>
	{% endfor %}
   </table>
    </div>
    <br>
    <p >
    实时行情
    </p>
    <div class="div-left">
        <img src = "http://image.sinajs.cn/newchart/min/n/{{ fullcode }}.gif" >
    </div>
    <div class="div-left">
        <img src="http://image.sinajs.cn/newchart/daily/n/{{ fullcode }}.gif " >
    </div>



{% endblock %}

templates/stockinhand.html
{% extends 'base.html' %}

{% block title %}
In Hand
{% endblock %}

{% block head %}

	<meta http-equiv="refresh" content="300">
{% endblock %}


{% block content %}

<h2>the stock in myhand</h2>

<div class='table_stock' style="text-align: center;">
<table border="1">
      <tr>
		  <th>股票代码</th>
		  <th>股票名称</th>
		  <th>现价</th>
		  <th>数量</th>
		  <th>市值</th>
          <th>涨幅</th>
		  <th>日盈亏</th>
          <th>总盈亏</th>
	  </tr>
	{% for item in stocks %}
      <tr>
		  <td> {{ item.code}} </td>
          <td><a  href="{% url 'stocks:stockdetail' item.code %}" > {{ item.name}} </a></td>
          <td>{{ item.close }}</td>
		  <td>{{ item.quantityinhand }}</td>
		  <td>{{ item.value }}</td>
		  <td>{{ item.ratio }}</td>
		  <td>{{ item.profit_day }}</td>
      	  <td>{{ item.profit }}</td>
	  </tr>
	{% endfor %}
   </table>
</div>
<p>市值：{{ profit.value }}</p>
<p>今天小赚：{{ profit.profit }}</p>

{% endblock %}

templates/totalbench.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
benchingmark
{% endblock %}


{% block head %}
      <script type="text/javascript" src="{% static 'js/echarts.min.js' %}"></script>
{% endblock %}



{% block content %}
<h1>welcome，it just is a cover</h1>
<h3>和沪深300比比</h3>
<div>
    <img src="{{ img }}">
<!--    <img src="my_plot.png" >-->
</div>


<div id="container" style="width: 800px;height:400px;"></div>
     <script type="text/javascript">
    var dom = document.getElementById("container");
    var myChart = echarts.init(dom);

    var series_data = [];
    var xAxis_data_300 = [];
    var xAxis_data_total = [];

    {% for bench in objs %}
        series_data.push("{{ bench.date }}")
        {#注意这里的双引号#}
        xAxis_data_300.push("{{ bench.bench_ratio}}")
        xAxis_data_total.push("{{ bench.total_ratio}}")
    {% endfor %}


    option = {
    title: {
        text: '对比300'
    },
    tooltip: {},

    legend: {
        data1: ['沪深300'],
        data2: ['你的资产'],
    },

    xAxis: {
        data: series_data
    },

    yAxis: {},

    series: [{
        name: '沪深300',
        type: 'line',
        //data: [5, 20, 36, 10, 10, 20]
        data: xAxis_data_300,
        smooth: true
    },

    {
        name: '你的资产',
        type: 'line',
        //data: [5, 20, 36, 10, 10, 20]
        data: xAxis_data_total,
        smooth: true,
        color: 'red',
    },

    ]
    };
    myChart.setOption(option);
    </script>


{% endblock %}

templates/trade.html
{% extends 'base.html' %}


{% block title %}
Trade
{% endblock %}


<head>
    <style>
        .container {
                display: flex; /* 使用 Flex 布局 */
                    }

        .item {
                flex: 1; /* 使每个标签具有相同的宽度 */
                margin-right: 10px; /* 可以根据需要设置标签之间的间距 */
                }
    </style>
</head>


{% block content %}
<h2> will buy or sell stock here!</h2>

 <form name="buyForm"  action="/buystock/"  method="POST">
        {% csrf_token %}
     <table>
         <tr>
             <td>股票代码：</td>
             <td>{{ stock_form.code }}</td>
         </tr>
         <tr>
             <td>股票金额：</td>
             <td>{{ buy_form.amount }}</td>
         </tr>
         <tr>
             <td>股票数量：</td>
             <td>{{ buy_form.quantity }}</td>
         </tr>

     </table>




     <div class="container" style="display:flex;margin-right: 200px">
         <div>
            <input type="radio" id="buy_radio" name="buy_radio" value="buy" checked />
            <label for="buy">买入</label>

            <input type="radio" id="send_radio" name="buy_radio" value="send" />
            <label for="send">送股</label>

        </div>
<!--        <div  style="position: absolute;left:150px">-->
<!--             <select name="stategy">-->
<!--                    <option value="">-请选择-</option>-->
<!--                    <option value="lmup">低市值</option>-->
<!--                    <option value="svr">svr</option>-->
<!--                    <option value="lowpe">lowpe</option>-->
<!--            </select>-->
<!--        </div>-->

     </div>

<!--        <div>{{buy_form.my_choice_radio}}</div>-->
<!--        <div>{{buy_form.my_choice_select}}</div>-->
<!--     </div>-->
    <input style="position: absolute;left:100px"     type="submit" name="bconfirm" value="交易" />
 </form>


<br>
<br>

<form name="sellForm"  action="/sellstock/"  method="POST">
        {% csrf_token %}

        <table>
         <tr>
             <td>股票代码：</td>
             <td>{{ stock_form.code }}</td>
         </tr>
         <tr>
             <td>股票金额：</td>
             <td>{{ sell_form.amount }}</td>
         </tr>
         <tr>
             <td>股票数量：</td>
             <td>{{ sell_form.quantity }}</td>
         </tr>

     </table>


    <div class="container" style="display:flex;margin-right: 200px">
    <div>
        <input type="radio" id="sell" name="sell_radio" value="sell" checked/>
        <label for="sell">卖出</label>

        <input type="radio" id="dividend" name="sell_radio" value="divi" />
        <label for="dividend">分红</label>
      </div>
<!--            <div  style="position: absolute;left:150px">-->
<!--             <select name="stategys">-->
<!--                    <option value="">-请选择-</option>-->
<!--                    <option value="lmup">低市值</option>-->
<!--                    <option value="svr">svr</option>-->
<!--                    <option value="lowpe">lowpe</option>-->
<!--            </select>-->
<!--        </div>-->
    </div>


    <div>
        <input style="position: absolute;left:100px" type="submit" name="bconfirm" value="卖出" />
    </div>
</form>
    <br>
<br>


<div class='table_record' style="text-align: center;">
<table border="1">
      <tr>
		  <th>时间</th>
		  <th>股票代码</th>
		  <th>股票名称</th>
		  <th>操作</th>
		  <th>数量</th>
		  <th>价格</th>
		  <th>金额</th>
	  </tr>
	{% for item in records %}
      <tr>
		  <td>{{ item.date }}</td>
		  <td> {{ item.stock.code }} </td>
		   <td><a  href="{% url 'stocks:stockdetail' item.stock.code %}" > {{ item.stock.name }} </a></td>
		  <td>{{ item.mark }}</td>
		  <td>{{ item.quantity }}</td>
		  <td>{{ item.price }}</td>
		  <td>{{ item.amount }}</td>
	  </tr>
	{% endfor %}
   </table>
</div>


{% endblock %}